In [5]:
import numpy as np

A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print (B.shape)


(4, 1)


In [3]:
print (B)


[[ 0.6845335 ]
 [ 1.8500246 ]
 [ 0.4940532 ]
 [ 0.35188171]]


In [4]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

print (c.shape)

(12288, 45)


In [9]:
# a.shape = (3,4)
# b.shape = (4,1)

a = np.random.randn(3,4)
b = np.random.randn(4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
    
print (c)

d = a + b.T

print (d)


[[  2.17232329  -0.03419104   0.11911408 ...,  10.58123081  -8.44745495
    6.89312459]
 [  0.08937751  -0.21684069   1.55008472 ...,   3.5573595    9.18786487
  -11.1181368 ]
 [  2.0954357   -1.04161315   1.43405281 ...,  30.03300538  -8.24398583
    1.7783824 ]
 ..., 
 [  9.10825896  21.62546872  -7.41007638 ...,  -0.91762485  18.27636274
  -11.81141328]
 [-14.03499845  -6.59059722  11.00674811 ...,  10.81765383  -4.75435434
   -2.53801487]
 [  3.09916388   3.69950337 -20.04115101 ...,  -4.87135327   0.91402482
   -8.3244755 ]]
[[ 2.17232329 -0.03419104  0.11911408 -0.27989   ]
 [ 0.08937751 -0.21684069  1.55008472 -0.34479249]
 [ 2.0954357  -1.04161315  1.43405281 -0.81315359]]


In [11]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

print (c.shape)

(3, 3)


In [13]:
print (a)
print (b)
print (c)

[[-0.27314634  0.02620391  1.32409119]
 [ 1.05622463 -0.75941479 -0.60261958]
 [ 2.15924945  0.18367988 -2.39503043]]
[[-0.02020956]
 [ 0.42492526]
 [ 0.38839369]]
[[  5.52016708e-03  -5.29569382e-04  -2.67592988e-02]
 [  4.48816524e-01  -3.22694527e-01  -2.56068280e-01]
 [  8.38638868e-01   7.13401081e-02  -9.30214712e-01]]
